#!/usr/bin/env bash

set -e

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG="install.conf.yaml"

cd "${BASEDIR}"
git submodule sync --quiet --recursive
git submodule update --init --recursive

"${BASEDIR}/dotbot/bin/dotbot" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
